// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'popup-arxiv-label'
  | 'popup-arxiv-tooltip'
  | 'popup-google-scholar-label'
  | 'popup-google-scholar-tooltip'
  | 'popup-ieee-label'
  | 'popup-ieee-tooltip'
  | 'popup-jstor-label'
  | 'popup-jstor-tooltip'
  | 'popup-pubmed-label'
  | 'popup-pubmed-tooltip'
  | 'popup-research-gate-label'
  | 'popup-research-gate-tooltip'
  | 'popup-semantic-scholar-label'
  | 'popup-semantic-scholar-tooltip'
  | 'popup-springer-label'
  | 'popup-springer-tooltip'
  | 'pref-arxiv-label'
  | 'pref-google-scholar-label'
  | 'pref-help'
  | 'pref-ieee-label'
  | 'pref-jstor-label'
  | 'pref-pubmed-label'
  | 'pref-research-gate-label'
  | 'pref-search-engines-description'
  | 'pref-search-engines-title'
  | 'pref-semantic-scholar-label'
  | 'pref-springer-label'
  | 'pref-title';
