// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'popup-google-scholar-label'
  | 'popup-google-scholar-tooltip'
  | 'pref-help'
  | 'pref-title';
