// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "searchEngines.googleScholar": boolean;
      "searchEngines.pubmed": boolean;
      "searchEngines.arxiv": boolean;
      "searchEngines.semanticScholar": boolean;
      "searchEngines.researchGate": boolean;
      "searchEngines.jstor": boolean;
      "searchEngines.ieee": boolean;
      "searchEngines.springer": boolean;
      "searchEngines.google": boolean;
      "customEngine.prefix": string;
    };
  }
}
